name: learn_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  material_design_icons_flutter: 7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
fonts:
  - family: Merienda
    fonts:
      - asset: fonts/Merienda-Regular.ttf
      - asset: fonts/Merienda-Bold.ttf
        weight: 700
      - asset: fonts/Merienda-ExtraBold.ttf
        weight: 800
      - asset: fonts/Merienda-Light.ttf
        weight: 300
      - asset: fonts/Merienda-SemiBold.ttf
        weight: 600
      - asset: fonts/Merienda-Black.ttf
        weight: 900
      - asset: fonts/Merienda-Medium.ttf
        weight: 500